# Generated by Django 3.2.5 on 2023-01-31 04:11

from django.db import migrations

from django.contrib.auth.models import User
from django.contrib.auth.models import Group

from datetime import datetime, timedelta
import time

def beginning(apps, schema_editor):
    
    # Суперпользователь id-1
    user = User.objects.create_superuser(username='root',
    email='culture291022@mail.ru',
    password='SsNn5678+-@')
    print("Суперпользователь создан")
    
    # Группа менеджеров
    managers = Group.objects.get_or_create(name = 'Managers')
    managers = Group.objects.get(name='Managers')
    print("Группа менеджеров создана")
    
    # Пользователь с ролью менеджера id2
    user = User.objects.create_user(username='manager', password='Ss0066+-', email='manager@mail.ru', first_name='Менеджер', last_name='')
    managers.user_set.add(user)
    print("Менеджер добавлен в группу менеджеров")

    # Простые пользователи (заявители) id3-12
    user = User.objects.create_user(username='user1', password='Uu0066+-', email='user1@mail.ru', first_name='Дина', last_name='Мусина')
    user = User.objects.create_user(username='user2', password='Uu0066+-', email='user2@mail.ru', first_name='Адия', last_name='Жунусова')
    user = User.objects.create_user(username='user3', password='Uu0066+-', email='user3@mail.ru', first_name='Айнура', last_name='Кенина')
    user = User.objects.create_user(username='user4', password='Uu0066+-', email='user4@mail.ru', first_name='Рустем', last_name='Какимов')
    user = User.objects.create_user(username='user5', password='Uu0066+-', email='user5@mail.ru', first_name='Алишер', last_name='Кабдуалиев')
    user = User.objects.create_user(username='user6', password='Uu0066+-', email='user6@mail.ru', first_name='Бауржан', last_name='Арыкбаев')
    user = User.objects.create_user(username='user7', password='Uu0066+-', email='user7@mail.ru', first_name='Алишер', last_name='Танатаров')
    user = User.objects.create_user(username='user8', password='Uu0066+-', email='user8@mail.ru', first_name='Мерует', last_name='Искакова')
    user = User.objects.create_user(username='user9', password='Uu0066+-', email='user9@mail.ru', first_name='Ольга', last_name='Муравьева')
    user = User.objects.create_user(username='user10', password='Uu0066+-', email='user10@mail.ru', first_name='Ақжарқын', last_name='Сансызбаева')
    print("Созданы простые пользователи")
        
    ##### Новости #####
    News = apps.get_model("house", "News")
    
    news = News()
    news.daten = '2022-11-16 00:00:00'
    news.title = ' В городе Павлодар пройдет III Республиканский конкурс исполнителей народных песен'
    news.details = """В ULR соберутся представители вокальных школ из разных уголков Казахстана. Кызылорда, Астана, Алматы, Актюбинск, Караганда, Павлодар, Костанай и др. - в целом около двух десятков участников.
    Почётным гостем и председателем жюри конкурса будет заслуженный деятель РК, профессор кафедры «Традиционной песни» Казахского национального университета, известный казахстанский жырши-термеши, ученый-фольклорист Алмасбек Алматов.
    Как подчеркивают организаторы конкурса, а это Павлодарское облуправление культуры и областной Центр самодеятельного народного творчества, цель — не только развитие вокального искусства нашей страны, казахского песенного творчества. Но и популяризация наследия местных композиторов среди молодежи, в целом обогащение духовных ценностей народа."""
    news.photo = 'images/news1.jpeg' 
    news.save()
        
    news = News()
    news.daten = '2022-11-19 00:00:00'
    news.title = 'Информация о III Республиканском конкурсе «Арқада Наушабайдың Нұржаны өткен...»'
    news.details = """17-18 ноября 2022 года в городе Павлодар в ГДК прошел III Республиканский конкурс исполнителей в жанре «жыр-терме» и «дастүрлі». 
    17 кандидатов из Кызылординской, Астанинской, Алматинской, Актюбинской, Карагандинской, Павлодарской областей приняли участие в республиканском песенном конкурсе. 
    Организатором конкурса выступил КГКП «Областной центр самодеятельного народного творчества и киновидеофонда» Управления культуры акимата Павлодарской области.  
    Цель конкурса : развитие казахского песенного творчества, сохранение и популяризация творческого наследия композитора среди казахстанской молодежи, развитие вокального искусства нашей страны, обогащение духовных ценностей народа."""
    news.photo = 'images/news2.jpeg' 
    news.save()
    
    news = News()
    news.daten = '2022-11-26 12:00:00'
    news.title = 'Информация областного конкурса cover-вокал «Best cover Pavlodar»'
    news.details = """Впервые в области прошел областной конкурс cover-вокала «Best cover Pavlodar». Конкурс вокалистов стартовал, в нашем доме культуры где собрались певцы, которые решили удивить зрителей и жюри своими талантами."""
    news.photo = 'images/news3.jpeg' 
    news.save()
        
    news = News()
    news.daten = '2022-12-09 12:00:00'
    news.title = 'Сегодня в каздрамтеатре творческий вечер певца, поэта, термеши, победителя республиканских конкурсов Кыдырбека Киысхана'
    news.details = """Он родился в Монголии. Но в 1991-м вместе с семьей Кыдырбек Киысхан переехал в село Карабатыр Камыстинского района. И за это время проявил массу своих талантов. Сегодня он не только наш коллега, корреспондент областной газеты, но и трехкратный(!) победитель областного айтыса школьников «Жас тұлпар», призер республиканских, международных айтысов. А также лауреат областных, республиканских, международных конкурсов жыршы-термеши.
    Коллеги по творческой площадке настоящим пропагандистом народных песен и местных композиторов, владеет многими музыкальными инструментами. Он стал одним из победителей международного мегапроекта «Мен қазақпын», лауреатом премии «Қазына» Павлодарского Клуба меценатов."""
    news.photo = 'images/news4.jpeg' 
    news.save()
    
    news = News()
    news.daten = '2022-12-16 12:00:00'
    news.title = 'В селе Айет в канун Дня Независимости народный театр поставил спектакль «Ақ-Келін»'
    news.details = """Пьеса основана на реальных событиях и написана корреспондентом «КН», Людмилой Фефеловой. Посвящена жизни и любви Бадрисафы (Александры Ивановны) и её супруга Ахмета Байтурсынова. Рассматривается два периода жизни женщины – ее счастливая молодость и трагический закат. После расстрела мужа в 1937 году (по другим данным в 1938) Бадрисафа прожила совсем недолго. Место ее захоронения до сих пор неизвестно, но она осталась в памяти людей, как символ верности, благородства и искренней любви."""
    news.photo = 'images/news5.jpeg' 
    news.save()
        
    news = News()
    news.daten = '2023-01-04 12:00:00'
    news.title = 'Асхат Оралов назначен министром культуры и спорта РК'
    news.details = """Указом Главы государства Оралов Асхат Раздыкович назначен Министром культуры и спорта Республики Казахстан.
    Оралов Асхат Раздыкович родился в 1990 году в Павлодарской области.
    Образование:
    Евразийский национальный университет им. Гумилева, 
    Московский государственный университет международных отношений МИД РФ.
    Трудовой стаж:
    В разные годы работал главным специалистом отдела по работе с молодежными организациями департамента социально-воспитательной работы, старшим специалистом отдела протокола Евразийского национального университета им. Гумилева.
    С 2014 по 2016 годы — первый заместитель председателя филиала «Нұр» партии «Нұр Отан».
    С 2016 по 2017 год — и. о. руководителя ГУ «Управление по вопросам молодежной политики г. Астаны».
    С 2017 по 2018 год — руководитель ГУ «Управление по вопросам молодежной политики г. Астаны».
    С января по август 2018 года — директор департамента молодежной политики Министерства по делам религий и гражданского общества РК.
    С 2018 по 2019 год - заместитель председателя Комитета по делам молодежи и семьи Министерства общественного развития РК.
    С 2019 по 2020 год - заместитель акима Павлодарской области.
    С 2020 по 2021 год - вице-министр информации и общественного развития РК.
    С 2021 по 2022 год – заместитель акима города Нур-Султан.
    С 2022 по настоящее время занимал должность исполнительного секретаря партии «AMANAT»."""
    news.photo = 'images/news6.jpeg' 
    news.save()
    
    news = News()
    news.daten = '2023-01-31 12:00:00'
    news.title = 'Областной центр самодеятельного народного творчества и киновидео фонда завершил прием годовых отчетов городских и районных отделов культуры Павлодарской области'
    news.details = """Руководители отделов культуры совместно с сотрудниками ДК отчитались о своей работе и поделились планами на будущий год. Мы благодарим руководителей отделов культуры городов и районов за проделанную работу, за понимание и ответственность в столь важном деле. И выражаем надежду что и этот год также завершится плодотворно."""
    news.photo = 'images/news7.jpeg' 
    news.save()

    print("Новости Ok")

    ##### Форум #####
    ##### Раздел форума #####
    Board = apps.get_model("house", "Board")
    ##### Тема форума #####
    Topic = apps.get_model("house", "Topic")
    ##### Сообщение (POST) для форума #####
    Post = apps.get_model("house", "Post")
    
    ##### Раздел №1 форума #####

    board = Board()
    board.name = 'Поготовка к празднованию Нового года'
    board.description = 'Вопросы касающиеся подготовки к празднованию Нового года' 
    board.save()

    topic = Topic()
    topic.subject = 'Организация новогоднего утренника для детей'
    topic.last_updated = datetime.now() 
    topic.board = board
    topic.starter_id = 3
    topic.views = 1
    topic.save()

    time.sleep(1)

    post = Post()
    post.message = 'Во сколько начнется утренник?'
    post.topic = topic
    post.created_at = datetime.now() - timedelta(minutes=2)
    #post.updated_at = datetime.now()
    post.created_by_id = 4
    #post.updated_by_id = 4
    post.save()

    time.sleep(1)

    post = Post()
    post.message = 'В 10 утра 30 декабря'
    post.topic = topic
    post.created_at = datetime.now() - timedelta(minutes=1)
    #post.updated_at = datetime.datetime.now()
    post.created_by_id = 5
    #post.updated_by_id = 1
    post.save()

    time.sleep(1)

    post = Post()
    post.message = 'Для родителей будет праздник :)?'
    post.topic = topic
    post.created_at = datetime.now() - timedelta(minutes=0)
    #post.updated_at = datetime.datetime.now()
    post.created_by_id = 7
    #post.updated_by_id = 7
    post.save()

    time.sleep(1)

    ##### Раздел №2 форума #####

    board = Board()
    board.name = 'Поготовка к празднованию Наурыз'
    board.description = 'Вопросы касающиеся подготовки к празднованию Наурыз' 
    board.save()

    topic = Topic()
    topic.subject = 'Праздничный дастархан'
    topic.last_updated = datetime.now() 
    topic.board = board
    topic.starter_id = 5
    topic.views = 1
    topic.save()

    time.sleep(1)
    
    post = Post()
    post.message = 'Кто готовит Наурыз Коже?'
    post.topic = topic
    post.created_at = datetime.now() - timedelta(minutes=4)
    #post.updated_at = datetime.now()
    post.created_by_id = 6
    #post.updated_by_id = 6
    post.save()

    time.sleep(1)
    
    post = Post()
    post.message = 'Могу я взяться за это дело'
    post.topic = topic
    post.created_at = datetime.now() - timedelta(minutes=3)
    #post.updated_at = datetime.now()
    post.created_by_id = 6
    #post.updated_by_id = 6
    post.save()

    time.sleep(1)
    
    topic = Topic()
    topic.subject = 'Праздничный концерт'
    topic.last_updated = datetime.now() 
    topic.board = board
    topic.starter_id = 5
    topic.views = 1
    topic.save()

    time.sleep(1)
    
    post = Post()
    post.message = 'Требуется домбра, сыграть емть кому'
    post.topic = topic
    post.created_at = datetime.now() - timedelta(minutes=4)
    #post.updated_at = datetime.now()
    post.created_by_id = 7
    #post.updated_by_id = 7
    post.save()

    time.sleep(1)
    
    post = Post()
    post.message = 'Я принесу'
    post.topic = topic
    post.created_at = datetime.now() - timedelta(minutes=4)
    #post.updated_at = datetime.now()
    post.created_by_id = 8
    #post.updated_by_id = 8
    post.save()

    ##### Раздел №3 форума #####
    board = Board()
    board.name = 'Поготовка к празднованию дня единства народа Казахстана'
    board.description = 'Вопросы касающиеся подготовки к празднованию дня единства народа Казахстана' 
    board.save()

    topic = Topic()
    topic.subject = 'Массовые мероприятия'
    topic.last_updated = datetime.now() 
    topic.board = board
    topic.starter_id = 5
    topic.views = 1
    topic.save()

    time.sleep(1)
    
    post = Post()
    post.message = 'Осуждаме место проведения паздничного концерта (внути СДК или на летней площадке)'
    post.topic = topic
    post.created_at = datetime.now() - timedelta(minutes=4)
    #post.updated_at = datetime.now()
    post.created_by_id = 9
    #post.updated_by_id = 9
    post.save()

    time.sleep(1)
    
    post = Post()
    post.message = 'Смотря по погоде'
    post.topic = topic
    post.created_at = datetime.now() - timedelta(minutes=3)
    #post.updated_at = datetime.now()
    post.created_by_id = 10
    #post.updated_by_id = 10
    post.save()

    ##### Раздел №4 форума #####

    board = Board()
    board.name = 'Вопрос специалисту'
    board.description = 'Задавайте свой вопрос специалисту' 
    board.save()

    print("Разделы форума Ok")
    print("Темы форума Ok")
    print("Сообщения форума Ok")

    ##### Отзывы #####

    Reviews = apps.get_model("house", "Reviews")
    
    reviews = Reviews()
    reviews.dater = '2023-01-08 15:00:00'
    reviews.rating = 5
    reviews.details = 'Я знаю этот дом культуры уже давно хорошее место для детей и молодежи и в нем есть библиотека для всех кто любит читать место супер'
    reviews.user_id = 3
    reviews.save()
    
    reviews = Reviews()
    reviews.dater = '2023-01-09 16:00:00'
    reviews.rating = 5
    reviews.details = 'Все хорошо, есть художественная школа,отличный преподаватель, так же есть местная сельская библиотека'
    reviews.user_id = 4
    reviews.save()
    
    reviews = Reviews()
    reviews.dater = '2023-01-10 17:00:00'
    reviews.rating = 5
    reviews.details = 'Старенький дом культуры, но внутри все довольно уютно.'
    reviews.user_id = 5
    reviews.save()
    
    reviews = Reviews()
    reviews.dater = '2023-01-11 18:00:00'
    reviews.rating = 5
    reviews.details = 'Замечательный коллектив.'
    reviews.user_id = 6
    reviews.save()
    
    reviews = Reviews()
    reviews.dater = '2023-01-12 19:00:00'
    reviews.rating = 5
    reviews.details = 'Очень интересно там присутствовать, каждому найдётся свое место). Единственное, сделать бы ремонт фасада и была бы Красота)'
    reviews.user_id = 7
    reviews.save()
    
    reviews = Reviews()
    reviews.dater = '2023-01-13 15:00:00'
    reviews.rating = 5
    reviews.details = 'Хорошие выступления'
    reviews.user_id = 8
    reviews.save()
    
    reviews = Reviews()
    reviews.dater = '2023-01-14 16:00:00'
    reviews.rating = 4
    reviews.details = 'Не хватаета культурных детских кружков, как было раньше.'
    reviews.user_id = 9
    reviews.save()
    
    reviews = Reviews()
    reviews.dater = '2023-01-15 17:00:00'
    reviews.rating = 5
    reviews.details = 'Шикарное место для концертов'
    reviews.user_id = 10
    reviews.save()
    
    reviews = Reviews()
    reviews.dater = '2023-01-16 18:00:00'
    reviews.rating = 5
    reviews.details = 'Добротный,уютный СДК!'
    reviews.user_id = 11
    reviews.save()
    
    reviews = Reviews()
    reviews.dater = '2023-01-17 19:00:00'
    reviews.rating = 5
    reviews.details = 'Чисто и красиво!'
    reviews.user_id = 12
    reviews.save()


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(beginning),       
    ]
